image: node:10.15.3

stages:
    - package

cache:
    paths:
      - node_modules/

docker:update:
    stage: package
    script:
        - rm -rf ./package-lock.json
        - npm install
        - IMAGE_TAG_NAME=$(echo $IMAGE_TAG | sed -r 's/(:\w*)\//\1_/')
        - docker login -u ssm -p $DOCKER_SSM_TOKEN docker.senior.com.br
        - docker image build -f dockerfile -t docker.senior.com.br/$IMAGE_TAG_NAME ./dist
        - docker push docker.senior.com.br/$IMAGE_TAG_NAME
      
