version: '2'
services:
    cus-analytics-backend:
        build:
            context: .
            dockerfile: dockerfile
        environment:
            NODE_ENV: production
        ports:
            - 3333:3333