GET http://localhost:3333/projects
###

GET http://localhost:3333/populate
###

GET http://localhost:3333/projects?name=mer&code=5070

###

DELETE http://localhost:3333/projects/5e46f8dec2f4a3276834282a

###

DELETE http://localhost:3333/projects/5e46f9ad2f7a5646181ded26